export const purchases = [
  { date: "2024-09-08", amount: 322 },
  { date: "2024-09-08", amount: 452 },
  { date: "2024-09-11", amount: 207 },
  { date: "2024-09-12", amount: 422 },
  { date: "2024-09-16", amount: 175 },
  { date: "2024-09-22", amount: 301 },
  { date: "2024-09-28", amount: 182 },
  { date: "2024-09-28", amount: 119 },
  { date: "2024-09-30", amount: 452 },
];

export const sales = [
  { date: "2024-08-31", amount: 450 },
  { date: "2024-09-18", amount: 134 },
  { date: "2024-09-21", amount: 401 },
  { date: "2024-09-25", amount: 410 },
  { date: "2024-09-28", amount: 314 },
];

export const salesDetails = [
  {
    bill_id: 1,
    date: "2024-08-31",
    amount: 450,
    discount: 0,
    payment_method: "cash",
    store: "store1",
    cashier: "cashier1",
    customer_name: "John Doe",
    description: "First-time customer",
  },
  {
    bill_id: 2,
    date: "2024-09-01",
    amount: 1200,
    discount: 100,
    payment_method: "card",
    store: "store2",
    cashier: "cashier2",
    customer_name: "Jane Smith",
  },
  {
    bill_id: 3,
    date: "2024-09-01",
    amount: 800,
    discount: 50,
    payment_method: "cash",
    store: "store1",
    cashier: "cashier3",
    customer_name: "Emily Davis",
    description: "Returning customer",
  },
  {
    bill_id: 4,
    date: "2024-09-02",
    amount: 600,
    discount: 0,
    payment_method: "cash",
    store: "store3",
    cashier: "cashier4",
    customer_name: "Michael Johnson",
  },
  {
    bill_id: 5,
    date: "2024-09-03",
    amount: 900,
    discount: 100,
    payment_method: "card",
    store: "store2",
    cashier: "cashier5",
    customer_name: "Laura Wilson",
    description: "Birthday discount applied",
  },
  {
    bill_id: 6,
    date: "2024-09-03",
    amount: 550,
    discount: 0,
    payment_method: "cash",
    store: "store1",
    cashier: "cashier1",
    customer_name: "Chris Brown",
  },
  {
    bill_id: 7,
    date: "2024-09-04",
    amount: 1100,
    discount: 50,
    payment_method: "card",
    store: "store2",
    cashier: "cashier2",
    customer_name: "Jessica Miller",
  },
  {
    bill_id: 8,
    date: "2024-09-05",
    amount: 450,
    discount: 20,
    payment_method: "cash",
    store: "store3",
    cashier: "cashier4",
    customer_name: "David Anderson",
    description: "Loyalty points redeemed",
  },
  {
    bill_id: 9,
    date: "2024-09-05",
    amount: 750,
    discount: 0,
    payment_method: "card",
    store: "store1",
    cashier: "cashier3",
    customer_name: "Olivia Harris",
  },
  {
    bill_id: 10,
    date: "2024-09-06",
    amount: 1300,
    discount: 150,
    payment_method: "card",
    store: "store2",
    cashier: "cashier5",
    customer_name: "Sophia Clark",
    description: "Bulk purchase discount",
  },
  {
    bill_id: 11,
    date: "2024-09-06",
    amount: 400,
    discount: 0,
    payment_method: "cash",
    store: "store1",
    cashier: "cashier1",
    customer_name: "Ava Lewis",
  },
  {
    bill_id: 12,
    date: "2024-09-07",
    amount: 600,
    discount: 30,
    payment_method: "card",
    store: "store3",
    cashier: "cashier4",
    customer_name: "Liam Walker",
  },
  {
    bill_id: 13,
    date: "2024-09-08",
    amount: 900,
    discount: 70,
    payment_method: "card",
    store: "store1",
    cashier: "cashier3",
    customer_name: "Ethan Hall",
  },
  {
    bill_id: 14,
    date: "2024-09-08",
    amount: 1500,
    discount: 100,
    payment_method: "card",
    store: "store2",
    cashier: "cashier2",
    customer_name: "Mason Lee",
  },
  {
    bill_id: 15,
    date: "2024-09-09",
    amount: 500,
    discount: 0,
    payment_method: "cash",
    store: "store3",
    cashier: "cashier4",
    customer_name: "Isabella Allen",
  },
  {
    bill_id: 16,
    date: "2024-09-10",
    amount: 1100,
    discount: 50,
    payment_method: "card",
    store: "store1",
    cashier: "cashier1",
    customer_name: "James Young",
  },
  {
    bill_id: 17,
    date: "2024-09-10",
    amount: 700,
    discount: 0,
    payment_method: "cash",
    store: "store2",
    cashier: "cashier5",
    customer_name: "Lucas Hernandez",
  },
  {
    bill_id: 18,
    date: "2024-09-11",
    amount: 600,
    discount: 30,
    payment_method: "card",
    store: "store1",
    cashier: "cashier3",
    customer_name: "Jack King",
  },
  {
    bill_id: 19,
    date: "2024-09-11",
    amount: 900,
    discount: 70,
    payment_method: "cash",
    store: "store3",
    cashier: "cashier4",
    customer_name: "Benjamin Wright",
  },
  {
    bill_id: 20,
    date: "2024-09-12",
    amount: 1400,
    discount: 100,
    payment_method: "card",
    store: "store2",
    cashier: "cashier2",
    customer_name: "Logan Scott",
    description: "VIP customer",
  },
  {
    bill_id: 21,
    date: "2024-09-12",
    amount: 800,
    discount: 50,
    payment_method: "cash",
    store: "store1",
    cashier: "cashier1",
    customer_name: "Alexander Adams",
  },
];

export const purchaseDetails = [
  {
    purchase_id: 1,
    date: "2024-09-12",
    supplier_name: "John Doe",
    inventory_name: "Inventory 2",
    amount: 4500,
    description: "Bulk purchase of office supplies",
  },
  {
    purchase_id: 2,
    date: "2024-09-13",
    supplier_name: "Jane Smith",
    inventory_name: "Inventory 5",
    amount: 3200,
  },
  {
    purchase_id: 3,
    date: "2024-09-14",
    supplier_name: "Michael Johnson",
    inventory_name: "Inventory 1",
    amount: 5800,
    description: "Purchase of raw materials",
  },
  {
    purchase_id: 4,
    date: "2024-09-15",
    supplier_name: "Emily Davis",
    inventory_name: "Inventory 3",
    amount: 2100,
  },
  {
    purchase_id: 5,
    date: "2024-09-16",
    supplier_name: "David Brown",
    inventory_name: "Inventory 4",
    amount: 6700,
    description: "Purchase for seasonal sale",
  },
  {
    purchase_id: 6,
    date: "2024-09-17",
    supplier_name: "Chris Lee",
    inventory_name: "Inventory 2",
    amount: 4900,
  },
  {
    purchase_id: 7,
    date: "2024-09-18",
    supplier_name: "Laura Wilson",
    inventory_name: "Inventory 1",
    amount: 3100,
    description: "Restocking inventory",
  },
  {
    purchase_id: 8,
    date: "2024-09-19",
    supplier_name: "Jessica Miller",
    inventory_name: "Inventory 6",
    amount: 2900,
  },
  {
    purchase_id: 9,
    date: "2024-09-20",
    supplier_name: "Sophia Anderson",
    inventory_name: "Inventory 4",
    amount: 5100,
  },
  {
    purchase_id: 10,
    date: "2024-09-21",
    supplier_name: "Ava Harris",
    inventory_name: "Inventory 5",
    amount: 4300,
    description: "Purchase for urgent client request",
  },
  {
    purchase_id: 11,
    date: "2024-09-22",
    supplier_name: "James Young",
    inventory_name: "Inventory 3",
    amount: 2800,
  },
  {
    purchase_id: 12,
    date: "2024-09-23",
    supplier_name: "Lucas Scott",
    inventory_name: "Inventory 2",
    amount: 3600,
  },
  {
    purchase_id: 13,
    date: "2024-09-24",
    supplier_name: "Benjamin Wright",
    inventory_name: "Inventory 1",
    amount: 6200,
    description: "Annual bulk purchase",
  },
  {
    purchase_id: 14,
    date: "2024-09-25",
    supplier_name: "Mason Lee",
    inventory_name: "Inventory 6",
    amount: 5200,
  },
  {
    purchase_id: 15,
    date: "2024-09-26",
    supplier_name: "Olivia Harris",
    inventory_name: "Inventory 5",
    amount: 3400,
  },
  {
    purchase_id: 16,
    date: "2024-09-27",
    supplier_name: "Ethan Hall",
    inventory_name: "Inventory 4",
    amount: 3900,
    description: "Stock for upcoming project",
  },
  {
    purchase_id: 17,
    date: "2024-09-28",
    supplier_name: "Liam King",
    inventory_name: "Inventory 3",
    amount: 2300,
  },
  {
    purchase_id: 18,
    date: "2024-09-29",
    supplier_name: "Isabella Allen",
    inventory_name: "Inventory 2",
    amount: 4500,
    description: "Urgent restocking",
  },
  {
    purchase_id: 19,
    date: "2024-09-30",
    supplier_name: "Logan Wright",
    inventory_name: "Inventory 1",
    amount: 2700,
  },
  {
    purchase_id: 20,
    date: "2024-10-01",
    supplier_name: "Alexander Adams",
    inventory_name: "Inventory 6",
    amount: 5400,
    description: "Special order for a new project",
  },
];
